### ISSUE TITLE
Add in web worker

### ISSUE THREAD

**Issue by rlaurente** [Shin-Tachibana/capacitor-fs#1]
- **I'm submitting a ...**
  [ ] bug report
  [] feature request
  [ ] question about the decisions made in the repository
  [*] question about how to use this project

Hi there

How can this be added in in web worker, specifically in importScripts function ? I tried adding it but I see multiple issues in adding dependency.

Thanks

**Comment by tachibana-shin** [comment]
What version of `@capacitor/filesystem` are you using?

**Comment by rlaurente** [comment]
The latest one. What I'm trying to achieve is to get this https://codesandbox.io/s/isomorphic-git10-in-a-worker-example-ejdoo?from-embed, wrapped in capacitor. 

I created a repo here: https://github.com/rlaurente/isomorphic-git-capacitor and it has example from LightningFS. What I'm trying to achieve is to replace it with your capacitor-fs. 

Thanks

**Comment by tachibana-shin** [comment]
Oh i understand your problem.

However `@capacitor/filesystem` can't work on webworker so `capacitor-fs` also doesn't work on webworker so i didn't make `umd` version of this package

If you want to use `capacitor-fs` on webworker (specifically `isomorphic-git`) pass `fs` as parameter and use [workercom](https://npmjs.org/package/workercom) as communicator.

Example use `isomorphic-git`, `capacitor-fs`. `workercom` in webworker:

git-clone.worker.ts
``` ts
import type {
  AuthCallback,
  AuthFailureCallback,
  AuthSuccessCallback,
  CallbackFsClient,
  MessageCallback,
  ProgressCallback,
  PromiseFsClient,
} from "isomorphic-git";
import { clone } from "isomorphic-git";
import http from "isomorphic-git/http/web";
import { expose } from "workercom";

export type GitCloneRemoteInterface = (config: {
  readonly fs: CallbackFsClient | PromiseFsClient;
  readonly onProgress?: ProgressCallback;
  readonly onMessage?: MessageCallback;
  readonly onAuth?: AuthCallback;
  readonly onAuthFailure?: AuthFailureCallback;
  readonly onAuthSuccess?: AuthSuccessCallback;
  readonly dir: string;
  readonly gitdir?: string;
  readonly url: string;
  readonly corsProxy?: string;
  readonly ref?: string;
  readonly singleBranch?: boolean;
  readonly noCheckout?: boolean;
  readonly noTags?: boolean;
  readonly remote?: string;
  readonly depth?: number;
  readonly since?: Date;
  // eslint-disable-next-line functional/prefer-readonly-type
  readonly exclude?: string[];
  readonly relative?: boolean;
  readonly headers?: { readonly [x: string]: string };
}) => Promise<void>;

function methods(): GitCloneRemoteInterface {
  return (config) =>
    clone({
      http,
      ...config,
    });
}

expose(methods());
```

use git-clone:
``` ts
import GitCloneWorker from "!worker-loader!./git-clone.worker"
import { wrap } from "workercom"
import fs from "./fs"

wrap(new GitCloneWorker())({
  fs,
  url: "<url repo>",
  dir: "/repo-clone",
  singleBranch: true,
  depth: 1
})
```

I have a repo using isomorphic-git on webworker you can see the source code here:
Workers: https://github.com/wecde/wecde/tree/vue-3-quasar/src/worker
Use git-clone: https://github.com/wecde/wecde/blob/vue-3-quasar/src/components/Git/Clone.vue#L113

**Comment by rlaurente** [comment]
Oh I see, thanks for this info!

Btw, do you have working example of capacitor-fs without using worker ? I able to integrate it in my end but after the pack file downloaded I get memory issue and crashes the mobile app.

**Comment by rlaurente** [comment]
Nevermind, I figure out that the problem is in iso git. It can't handle big repos and able to clone small repos in mobile app.

Thanks
