### ISSUE TITLE
Is that possible to read files from Photo Library?

### ISSUE THREAD

**Issue by bushev** [Shin-Tachibana/capacitor-fs#3]
Hello,

Is that possible to read files from Photo Library?

Like:

```
/var/mobile/Media/DCIM/100APPLE/***.JPG
```

**Comment by tachibana-shin** [comment]
Hello,

This plugin is not integrated with this function if you want to get photos/video from photo library please use [capacitor-plugin-photoviewer](https://github.com/capacitor-community/photoviewer)

You can read a file like that with a plug-in, but I don't think iOS will allow you to read the word `/var/mobile` for security reasons, but Android is OK.

**Comment by tachibana-shin** [comment]
closed for no new updates
