### ISSUE TITLE
readdir has wrong type

### ISSUE THREAD

**Issue by Ralle** [Shin-Tachibana/capacitor-fs#5]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

The TypeScript definition for `readdir` is incorrect. The type is presented as:
```
readdir: (path: string) => Promise<readonly string[]>;
```

But is actually
```
readdir: (path: string) => Promise<readonly SomeKindOfFile[]>;
```

Where an example of `SomeKindOfFile` can be seen here:
```
{
    ctime: "1685222746852"
    mtime: "1685222746862"
    name: "149e76c2bdf06535eccc518d969d848f13158089.mp3"
    size: 11607479
    type: "file"
    uri: "file:///private/var/mobile/Containers/Data/Application/6A855C5A-1330-433A-B1D4-B648E9992B55/Library/Caches/149e76c2bdf06535eccc518d969d848f1…"
}
```

**Comment by tachibana-shin** [comment]
Looks like you're using a new version of `@capacitor/filesystem`. this becomes incompatible with `capacitor-fs` I will upgrade this plugin as soon as possible

**Comment by tachibana-shin** [comment]
please check the new version of the plugin and see if the problem is fixed

**Comment by Ralle** [comment]
Looks like it's still there:
https://github.com/tachibana-shin/capacitor-fs/blob/master/src/index.ts#L181

**Comment by tachibana-shin** [comment]
> Looks like it's still there: https://github.com/tachibana-shin/capacitor-fs/blob/master/src/index.ts#L181

Fix in line: https://github.com/tachibana-shin/capacitor-fs/blob/master/src/index.ts#L187

this plugin is designed to follow the standard specification of `fs` so `readonly string[]` is reasonable I have modified it so that `files` returns the `names' of no
